### ISSUE TITLE
libgcc not found

### ISSUE THREAD

**Issue by markfirmware** [frol/docker-alpine-fpc#2]
[log.txt](https://github.com/Docker-Hub-frolvlad/docker-alpine-fpc/files/5877434/log.txt)

**Comment by frol** [comment]
@markfirmware Have you noticed any issue except the message log being printed? `fpc` seems to be working fine for me.

**Comment by markfirmware** [comment]
I thought that there was a problem but upon retesting, there is not!

I will leave it to you to keep this issue open for tracking the libgcc error or to close it. I am not experiencing any problems. Thanks!

FYI I forked your repo and added .gitpod.yml. To try it use the ready-to-code badge at https://github.com/markfirmware/docker-alpine-fpc-http-server#readme

**Comment by frol** [comment]
I have observed this error for years, but it never caused any problems for me, so I am going to close this issue.

I am glad my image empowers others!

Thanks for your time! Don't hesitate to file an issue if there is a bug in my images
